### ISSUE TITLE
Error: ...(result = MULTITREE_CHILD_NOT_FOUND)

### ISSUE THREAD

**Issue by handcyclist** [Azure-Samples/iot-hub-c-raspberrypi-client-app#24]
Hello:
Some code is not working as intended.
I get the following error

Info: Sending message: { "deviceId": "Raspberry Pi - C", "messageId": 1, "temperature": 24.889999, "humidity": 72.779999 }
Info: Message sent to Azure IoT Hub
Error: Time:Tue Mar 13 19:48:35 2018 File:/home/pi/Source/azure-iot-sdk-c/serializer/src/multitree.c Func:MultiTree_GetLeafValue Line:735 (result = MULTITREE_CHILD_NOT_FOUND)
Info: Sending message: { "deviceId": "Raspberry Pi - C", "messageId": 2, "temperature": 21.320000, "humidity": 77.250000 }
Info: Message sent to Azure IoT Hub
...
and then message 3, 4, etc without more errors

******Code in main.c for the iot-hub-c-raspberrypi-client-app sample******

 I suspect this code line is wrong, or incomplete, or should not be there:
Line 374:     IoTHubClient_LL_SetDeviceTwinCallback(iotHubClientHandle, twinCallback, NULL);

What does this code line do?
Line 375:     IoTHubClient_LL_SetOption(iotHubClientHandle, "product_info", "HappyPath_RaspberryPi-C");

I suspect this function is tried to be called by line 374
Line 139:     void twinCallback(
    DEVICE_TWIN_UPDATE_STATE updateState,
    const unsigned char *payLoad,
    size_t size,
    void *userContextCallback)

**Comment by SLdragon** [comment]
@handcyclist  Sorry for the late, this error can be safely ignored, because the code is try to read "interval" property from device twin which is not exist, and the follow-up tutorial will show you how to update the device twin.

You can find the tutorial by the link below:
https://docs.microsoft.com/en-gb/azure/iot-hub/iot-hub-device-management-iothub-explorer

We will fix this in the future release as this is not an error but just a warning.

Thanks
